name: IPTV-Asia

on:
#  schedule:
#    - cron: 0 9,15,22 * * ? 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download
        run: |
          rm -f ./m3u/asia.m3u && wget https://iptv-org.github.io/iptv/regions/asia.m3u > ./m3u/asia.m3u
         

      - name: Commit And Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "update src"
          git push origin main
